import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { BellRing, ArrowUpRight } from "lucide-react";
import { ApiErrorState, EmptyState } from "@/components/DataStates";
import { StatusPill } from "@/components/StatusPill";
import { towersQuery, regionsQuery, operatorsQuery } from "@/lib/queries";
import { relativeTime, toTowerView } from "@/lib/operations";
export const Route=createFileRoute("/alarmes")({loader:async({context})=>{await Promise.all([context.queryClient.ensureQueryData(towersQuery),context.queryClient.ensureQueryData(regionsQuery),context.queryClient.ensureQueryData(operatorsQuery)])},head:()=>({meta:[{title:"Alarmes — ANTOSC"},{name:"description",content:"Fila operacional de falhas e anomalias de recolha."},{property:"og:title",content:"Alarmes — ANTOSC"},{property:"og:description",content:"Fila operacional de falhas e anomalias de recolha."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page,errorComponent:({error,reset})=><ApiErrorState error={error} retry={reset}/>,notFoundComponent:()=> <EmptyState title="Sem alarmes" text="Não existem alarmes operacionais."/>});
function Page(){const{data:t}=useSuspenseQuery(towersQuery),{data:r}=useSuspenseQuery(regionsQuery),{data:o}=useSuspenseQuery(operatorsQuery);const alarms=t.data.map(x=>toTowerView(x,r.data,o.data)).filter(x=>x.observedState!=="healthy").sort((a,b)=>Number(b.observedState==="critical")-Number(a.observedState==="critical"));return <div className="space-y-5"><div><h2 className="text-2xl font-bold">Alarmes e falhas</h2><p className="mt-1 text-sm text-muted-foreground">{alarms.length} sites exigem validação, ordenados por impacto.</p></div><section className="border border-border bg-card">{alarms.length?alarms.map(a=><Link key={a.tower_id} to="/torres/$torreId" params={{torreId:a.tower_id}} search={{tab:"eventos"}} className="grid items-center gap-3 border-b border-border p-4 last:border-0 hover:bg-muted/40 md:grid-cols-[180px_1fr_180px_120px_24px]"><StatusPill state={a.observedState} label={a.observedLabel}/><div><p className="text-sm font-semibold">{a.name}</p><p className="mt-0.5 text-[11px] text-danger">{a.last_collection_error||"Estado operacional requer validação"}</p></div><span className="text-xs text-muted-foreground">{a.regionName}</span><span className="font-mono text-[10px] text-muted-foreground">{relativeTime(a.last_collected_at)}</span><ArrowUpRight className="h-4 w-4 text-muted-foreground"/></Link>):<EmptyState title="Operação estável" text="Nenhuma falha foi identificada nos dados atuais."/>}</section></div>}
