import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { MapPin } from "lucide-react";
import { ApiErrorState, EmptyState } from "@/components/DataStates";
import { StatusPill } from "@/components/StatusPill";
import { towersQuery,regionsQuery,operatorsQuery } from "@/lib/queries";
import { toTowerView } from "@/lib/operations";
export const Route=createFileRoute("/mapa")({loader:async({context})=>{await Promise.all([context.queryClient.ensureQueryData(towersQuery),context.queryClient.ensureQueryData(regionsQuery),context.queryClient.ensureQueryData(operatorsQuery)])},head:()=>({meta:[{title:"Mapa operacional — ANTOSC"},{name:"description",content:"Distribuição geográfica dos sites com coordenadas confirmadas."},{property:"og:title",content:"Mapa operacional — ANTOSC"},{property:"og:description",content:"Distribuição geográfica dos sites com coordenadas confirmadas."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page,errorComponent:({error,reset})=><ApiErrorState error={error} retry={reset}/>,notFoundComponent:()=> <EmptyState title="Sem localizações" text="Não existem coordenadas confirmadas."/>});
function Page(){const{data:t}=useSuspenseQuery(towersQuery),{data:r}=useSuspenseQuery(regionsQuery),{data:o}=useSuspenseQuery(operatorsQuery);const all=t.data.map(x=>toTowerView(x,r.data,o.data)),mapped=all.filter(x=>x.hasCoordinates),missing=all.length-mapped.length;return <div className="space-y-5"><div><h2 className="text-2xl font-bold">Mapa operacional</h2><p className="mt-1 text-sm text-muted-foreground">{mapped.length} sites com coordenadas confirmadas · {missing} sem localização.</p></div><div className="grid min-h-[560px] border border-border bg-card lg:grid-cols-[1fr_320px]"><div className="relative overflow-hidden bg-muted"><div className="absolute inset-0 opacity-50" style={{backgroundImage:"linear-gradient(var(--border) 1px, transparent 1px), linear-gradient(90deg, var(--border) 1px, transparent 1px)",backgroundSize:"48px 48px"}}/><div className="relative grid h-full place-items-center p-8 text-center"><div><MapPin className="mx-auto h-8 w-8 text-primary"/><h3 className="mt-3 text-sm font-semibold">Visualização cartográfica por integrar</h3><p className="mt-1 max-w-sm text-xs text-muted-foreground">As coordenadas reais estão listadas ao lado. Nenhuma localização aproximada foi criada.</p></div></div></div><aside className="overflow-y-auto border-l border-border">{mapped.map(x=><Link key={x.tower_id} to="/torres/$torreId" params={{torreId:x.tower_id}} search={{tab:"localização"}} className="block border-b border-border p-4 hover:bg-muted/40"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold">{x.name}</p><StatusPill compact state={x.observedState} label={x.observedLabel}/></div><p className="mt-1 font-mono text-[10px] text-muted-foreground">{x.latitude}, {x.longitude}</p></Link>)}</aside></div></div>}
