import { createFileRoute } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { Download, FileSpreadsheet } from "lucide-react";
import { ApiErrorState, EmptyState } from "@/components/DataStates";
import { Button } from "@/components/ui/button";
import { towersQuery,regionsQuery,operatorsQuery } from "@/lib/queries";
import { formatPercent,toTowerView,validAvailability } from "@/lib/operations";
export const Route=createFileRoute("/relatorios")({loader:async({context})=>{await Promise.all([context.queryClient.ensureQueryData(towersQuery),context.queryClient.ensureQueryData(regionsQuery),context.queryClient.ensureQueryData(operatorsQuery)])},head:()=>({meta:[{title:"Relatórios — ANTOSC"},{name:"description",content:"Exportações operacionais com indicação de qualidade dos dados."},{property:"og:title",content:"Relatórios — ANTOSC"},{property:"og:description",content:"Exportações operacionais com indicação de qualidade dos dados."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Page,errorComponent:({error,reset})=><ApiErrorState error={error} retry={reset}/>,notFoundComponent:()=> <EmptyState title="Sem dados" text="Não existem dados para exportar."/>});
function Page(){const{data:t}=useSuspenseQuery(towersQuery),{data:r}=useSuspenseQuery(regionsQuery),{data:o}=useSuspenseQuery(operatorsQuery);const rows=t.data.map(x=>toTowerView(x,r.data,o.data));const download=()=>{const esc=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[["ID","Site","Estado observado","Região","Fabricante","Última recolha válida","Disponibilidade 30d"],...rows.map(x=>[x.tower_id,x.name,x.observedLabel,x.regionName,x.vendor,x.last_successful_at||"Não reportado",formatPercent(validAvailability(x))])].map(row=>row.map(esc).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="antosc-sites.csv";a.click();URL.revokeObjectURL(a.href)};return <div className="space-y-5"><div><h2 className="text-2xl font-bold">Relatórios</h2><p className="mt-1 text-sm text-muted-foreground">Exportações identificam leituras ausentes em vez de preencher valores.</p></div><section className="flex flex-wrap items-center justify-between gap-5 border border-border bg-card p-5"><div className="flex gap-4"><span className="grid h-11 w-11 place-items-center rounded-md bg-info-soft text-primary"><FileSpreadsheet className="h-5 w-5"/></span><div><h3 className="text-sm font-semibold">Inventário operacional</h3><p className="mt-1 text-xs text-muted-foreground">{rows.length} sites · CSV · estado, região, fabricante e qualidade da disponibilidade</p></div></div><Button onClick={download}><Download/>Transferir CSV</Button></section></div>}
