/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlarmesRouteImport } from './routes/alarmes'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as OperadoresRouteImport } from './routes/operadores'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as TorresRouteImport } from './routes/torres'
import { Route as TorresTorreIdRouteImport } from './routes/torres.$torreId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmesRoute = AlarmesRouteImport.update({
  id: '/alarmes',
  path: '/alarmes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadoresRoute = OperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const TorresRoute = TorresRouteImport.update({
  id: '/torres',
  path: '/torres',
  getParentRoute: () => rootRouteImport,
} as any)
const TorresTorreIdRoute = TorresTorreIdRouteImport.update({
  id: '/$torreId',
  path: '/$torreId',
  getParentRoute: () => TorresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarmes': typeof AlarmesRoute
  '/mapa': typeof MapaRoute
  '/operadores': typeof OperadoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/torres': typeof TorresRouteWithChildren
  '/torres/$torreId': typeof TorresTorreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarmes': typeof AlarmesRoute
  '/mapa': typeof MapaRoute
  '/operadores': typeof OperadoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/torres': typeof TorresRouteWithChildren
  '/torres/$torreId': typeof TorresTorreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarmes': typeof AlarmesRoute
  '/mapa': typeof MapaRoute
  '/operadores': typeof OperadoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/torres': typeof TorresRouteWithChildren
  '/torres/$torreId': typeof TorresTorreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarmes'
    | '/mapa'
    | '/operadores'
    | '/relatorios'
    | '/torres'
    | '/torres/$torreId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarmes'
    | '/mapa'
    | '/operadores'
    | '/relatorios'
    | '/torres'
    | '/torres/$torreId'
  id:
    | '__root__'
    | '/'
    | '/alarmes'
    | '/mapa'
    | '/operadores'
    | '/relatorios'
    | '/torres'
    | '/torres/$torreId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmesRoute: typeof AlarmesRoute
  MapaRoute: typeof MapaRoute
  OperadoresRoute: typeof OperadoresRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TorresRoute: typeof TorresRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarmes': {
      id: '/alarmes'
      path: '/alarmes'
      fullPath: '/alarmes'
      preLoaderRoute: typeof AlarmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operadores': {
      id: '/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof OperadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torres': {
      id: '/torres'
      path: '/torres'
      fullPath: '/torres'
      preLoaderRoute: typeof TorresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torres/$torreId': {
      id: '/torres/$torreId'
      path: '/$torreId'
      fullPath: '/torres/$torreId'
      preLoaderRoute: typeof TorresTorreIdRouteImport
      parentRoute: typeof TorresRoute
    }
  }
}

interface TorresRouteChildren {
  TorresTorreIdRoute: typeof TorresTorreIdRoute
}

const TorresRouteChildren: TorresRouteChildren = {
  TorresTorreIdRoute: TorresTorreIdRoute,
}

const TorresRouteWithChildren =
  TorresRoute._addFileChildren(TorresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmesRoute: AlarmesRoute,
  MapaRoute: MapaRoute,
  OperadoresRoute: OperadoresRoute,
  RelatoriosRoute: RelatoriosRoute,
  TorresRoute: TorresRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
