/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorresRouteImport } from './routes/torres'
import { Route as TorresTorreIdRouteImport } from './routes/torres.$torreId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorresRoute = TorresRouteImport.update({
  id: '/torres',
  path: '/torres',
  getParentRoute: () => rootRouteImport,
} as any)
const TorresTorreIdRoute = TorresTorreIdRouteImport.update({
  id: '/$torreId',
  path: '/$torreId',
  getParentRoute: () => TorresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/torres': typeof TorresRouteWithChildren
  '/torres/$torreId': typeof TorresTorreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/torres': typeof TorresRouteWithChildren
  '/torres/$torreId': typeof TorresTorreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/torres': typeof TorresRouteWithChildren
  '/torres/$torreId': typeof TorresTorreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/torres' | '/torres/$torreId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/torres' | '/torres/$torreId'
  id: '__root__' | '/' | '/torres' | '/torres/$torreId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TorresRoute: typeof TorresRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torres': {
      id: '/torres'
      path: '/torres'
      fullPath: '/torres'
      preLoaderRoute: typeof TorresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torres/$torreId': {
      id: '/torres/$torreId'
      path: '/$torreId'
      fullPath: '/torres/$torreId'
      preLoaderRoute: typeof TorresTorreIdRouteImport
      parentRoute: typeof TorresRoute
    }
  }
}

interface TorresRouteChildren {
  TorresTorreIdRoute: typeof TorresTorreIdRoute
}

const TorresRouteChildren: TorresRouteChildren = {
  TorresTorreIdRoute: TorresTorreIdRoute,
}

const TorresRouteWithChildren =
  TorresRoute._addFileChildren(TorresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TorresRoute: TorresRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
